server:
  port: 8088

spring:
  application:
    name: mooreGateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: moore
    url: jdbc:mysql://49.235.208.185:3307/manager?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT

zuul:
  host:
    connect-timeout-millis: 2000
  routes:
    product:
      customSensitiveHeaders: true
      serviceId: mooreSdata
      path: /product/**
      strip-prefix: false
#    login:
#      customSensitiveHeaders: true
#      serviceId: mooreGateway
#      path: /login
#      strip-prefix: false

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.moore.model.entity
  global-config:
    db-config:
      id-type: auto

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://49.235.208.185:8099/eureka/
    fetch-registry: true
    register-with-eureka: true